
$(document).ready(function(){
  $("#owl-1").owlCarousel();
  $("#owl-2").owlCarousel();
  $("#owl-3").owlCarousel();
  $("#owl-4").owlCarousel();
});

$('#owl-1').owlCarousel({
    loop:true,
    margin:10,
    responsiveClass:true,
    responsive:{
        250:{
            items:1,
            nav:false
        },
        450:{
            items:1,
            nav:false
        },
        576:{
            items:2,
            nav:false
        },
        768:{
            items:2,
            nav:false
        },
        1000:{
            items:2,
            nav:false
        },
        1300:{
            items:2,
            nav:false
        },
        1310:{
            items:3,
            nav:false
        }
    }
})

$('#owl-2').owlCarousel({
  loop:true,
  margin:10,
  responsiveClass:true,
  responsive:{
    250:{
        items:1,
        nav:false
    },
    450:{
        items:1,
        nav:false
    },
    576:{
        items:2,
        nav:false
    },
    768:{
        items:2,
        nav:false
    },
    1000:{
        items:2,
        nav:false
    },
    1300:{
        items:2,
        nav:false
    },
    1310:{
        items:3,
        nav:false
    }
  }
})

$('#owl-3').owlCarousel({
  loop:true,
  margin:10,
  responsiveClass:true,
  responsive:{
    250:{
        items:1,
        nav:false
    },
    450:{
        items:1,
        nav:false
    },
    576:{
        items:2,
        nav:false
    },
      768:{
          items:3,
          nav:false
      },
      1000:{
          items:3,
          nav:false
      },
      1400:{
        items:3,
        nav:false
    }
  }
})

$('#owl-4').owlCarousel({
    loop:true,
    margin:10,
    responsiveClass:true,
    responsive:{
        250:{
            items:1,
            nav:false
        },
        450:{
            items:1,
            nav:false
        },
        768:{
            items:3,
            nav:false
        },
        1000:{
            items:3,
            nav:false
        }
    }
  })

